### PR TITLE
Fix/11 check GitHub

### PR DESCRIPTION
**Pull request by dwlfrth**

### CODE REVIEW

**Comment by dwlfrth** [comment]
Review me

**Comment by julsemaan** [comment]
Would be cleaner if the function github_available would return 0/1 on success/failure and the if condition evaluates the return of that function instead of polluting the environment

**Comment by dwlfrth** [comment]
Review me

**Comment by julsemaan** [comment]
Script still works as intended and github API down detection is working

Merging + updating monitoring scripts

**Pull request merged**
